### ISSUE TITLE
Rationale for joining connected and commonLikes events

### ISSUE THREAD

**Issue by lppedd** [coal0/python-omegle#2]
In a typical Omegle response body you would have
```
[["connected"], ["commonLikes", ["Soccer"]], ...
```
So what is the rationale for joining them in a single event?  
For you that meant you had to specialize event parsing for each chat type.

**Comment by coal0** [comment]
Because you would never get a `commonLikes`  event without a `connected` event. If you do, something is wrong. Adding the common interests as an argument works well with the rest of the API.

**Comment by lppedd** [comment]
@coal0 thanks! Sounds good.
